### ISSUE TITLE
Issue 6 for milestone 3: Training the Model

### ISSUE THREAD

**Issue by joycheptoo** [joycheptoo/BIProject-136804#6]
- [x] Data Splitting
- [x] Bootstrapping
- [x] Cross validation(basic, repeated, or LOOCV)
- [x] Model training for either classification, regression, association or clustering(as applicable)
- [ ] Model performance comparison using resampling(for classification and regression)

**Comment by joycheptoo** [comment]
almost there!
